name: test

on:
  push:
    branches:
      - main
    tags:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, World!"
